import * as React from "react"
import { SVG } from './styles'
export function LoadingIcon(props) {
  return (
    <SVG
      style={{
        margin: "0",
        background: "#ffcc00",
      }}
      width={100}
      height={100}
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
      display="block"
      {...props}
    >
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.9666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(12 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.9333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(24 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.9s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(36 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.8666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(48 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.8333333333333334s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(60 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.8s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(72 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.7666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(84 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.7333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(96 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.7s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(108 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.6666666666666666s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(120 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.6333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(132 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.6s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(144 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.5666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(156 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.5333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(168 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.5s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(180 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.4666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(192 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.43333333333333335s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(204 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.4s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(216 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.36666666666666664s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(228 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.3333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(240 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.3s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(252 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.26666666666666666s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(264 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.23333333333333334s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(276 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.2s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(288 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.16666666666666666s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(300 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.13333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(312 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.1s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(324 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.06666666666666667s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(336 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="-0.03333333333333333s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x={49.5}
        y={35.5}
        rx={0.5}
        ry={4.5}
        width={1}
        height={9}
        fill="#e535ab"
        transform="rotate(348 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1s"
          begin="0s"
          repeatCount="indefinite"
        />
      </rect>
    </SVG>
  )
}


